# Generated by Django 5.1.1 on 2024-09-10 23:14

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="astronomyshow",
            name="images",
            field=models.ImageField(
                null=True, upload_to=booking.models.astronomy_show_image_file_path
            ),
        ),
    ]
